---
- name: Install packages for Debian
  vars:
    common_required_packages:
      - git
  apt:
    name: "{{ common_required_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_pkg_mgr == 'apt'
